Project import generated by Copybara.
GitOrigin-RevId: 729b42b66a7d2f7537a0ae0e7ce10facb0d44856
Change-Id: Ib0dd3ec92c48e62ef1143500a7e658de1695fa44

diff --git a/demos/tax-office/k8s/helm/templates/jupyter/jupyter-deployment.yaml b/demos/tax-office/k8s/helm/templates/jupyter/jupyter-deployment.yaml
--- a/demos/tax-office/k8s/helm/templates/jupyter/jupyter-deployment.yaml
+++ b/demos/tax-office/k8s/helm/templates/jupyter/jupyter-deployment.yaml
@@ -85,17 +85,34 @@ spec:
           env:
             - name: JUPYTER_ENABLE_LAB
               value: "yes"
-            - name: JUPYTER_TOKEN
-              value: {{ .Values.jupyter.token | quote }}
+            - name: JUPYTER_RAW_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  name: jupyter-notebook-secret
+                  key: jupyter-raw-password
 
           volumeMounts:
             - name: notebook-volume
               mountPath: /home/jovyan  # The home directory for 'jovyan' user
-          command: ["start-notebook.sh"]
+          command: ["sh", "-c"]
           args:
-            - "--NotebookApp.password=$(JUPYTER_TOKEN)"
-            - "--NotebookApp.token=''"
-            - "--NotebookApp.trust_xheaders=True"
+            - |
+              if [ -z "$JUPYTER_RAW_PASSWORD" ]; then
+                echo "Error: JUPYTER_RAW_PASSWORD is not set"
+                exit 1
+              fi
+              HASHED_PW=$(python3 -c "
+              import os
+              try:
+                  from jupyter_server.auth import passwd
+              except ImportError:
+                  from notebook.auth import passwd
+              print(passwd(os.environ['JUPYTER_RAW_PASSWORD']))
+              ")
+              exec start-notebook.sh \
+                --NotebookApp.password="${HASHED_PW}" \
+                --NotebookApp.token='' \
+                --NotebookApp.trust_xheaders=True
 
       volumes:
         - name: notebook-volume
